# GitHub Action Release
# MSI-B360-Catalina-EFI

name: test

on:
  push:
    paths:
      - "ReleaseTag"
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/SuperNG6/MSI-B360-Catalina-EFI
  REPO_BRANCH: master
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git wget unzip
        sudo timedatectl set-timezone "$TZ"

    - name: Clone source code
      working-directory: /tmp
      run: |
        git clone $REPO_URL -b $REPO_BRANCH hackintosh
        ln -sf /tmp/hackintosh $GITHUB_WORKSPACE/hackintosh
        echo "EFI_PATH=$GITHUB_WORKSPACE/hackintosh" >> $GITHUB_ENV

    - name: Packaging EFI
      run: |
        cd $GITHUB_WORKSPACE/hackintosh
        zip -rq AMD.5500XT+IGPU.iMac19.1.zip ./AMD\ 5500XT+IGPU\ \(iMac19\,1\)/
        zip -rq AMD.GPU+IGPU.iMac19.1.zip ./AMD\ GPU+IGPU\ \(iMac19\,1\)
        zip -rq ONLY.AMD.GPU.iMacPro1.1.zip ./ONLY\ AMD\ GPU\ \(iMacPro1\,1\)
        zip -rq ONLY.IGPU.Macmini8.1.zip ./ONLY\ IGPU\ \(Macmini8\,1\)
        ls -l

    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "::set-output name=release_tag::$(cat ReleaseTag)"
        echo "::set-output name=status::success"
        cat ReleaseTag

    - name: Upload EFI to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: MSI-B360-${{ steps.tag.outputs.release_tag }}
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: Changelog
        files: |
          ${{ env.EFI_PATH }}/*.zip

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 1
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}